# Site settings
title: TNC NA Science
email: dmajka@tnc.org
url: https://thenatureconservancy.github.io
description: "Web dev and cartography portfolio"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F
  
# Footer settings
footer:
  copyright: The Nature Conservancy
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/thenatureconservancy

# Postal address (add as many lines as necessary)
address:
  - line: 1101 W River Pkwy, Suite 200
  - line: Minneapolis, MN 55415
  
# Credits content
credits: 'Freelance is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
